### ISSUE TITLE
Validation error: Parse error at 1:19 near token ]

### ISSUE THREAD

**Issue by tarjelavik** [IIIF/presentation-validator#107]
I get this error when trying to validate this manifest: https://marcus-manifest-api.vercel.app/api/iiif/manifest/ubb-ms-0003. The manifest validates as json-ld, but gives this error on the IIIF validator. 

> Validation Error: Presentation Validator bug: "Parse error at 1:19 near token ] (])". 

https://iiif.io/api/presentation/validator/service/validate?format=json&version=3.0&url=https://marcus-manifest-api.vercel.app/api/iiif/manifest/ubb-ms-0003

Any clues to what is happening?

**Comment by glenrobson** [comment]
Thanks for reporting. You were the first to try a version 3.0 manifest with over 10 pages so a bug was laying in wait to be discovered. The bug is now fixed.

If you try and validate your manifest again in 30mins or so you should see the validation errors.

**Comment by tarjelavik** [comment]
Thanks for the quick fix! 👍

I found the minor issues and now the manifests validates 😄.
