### ISSUE TITLE
Validator does not test for label in v3 manifests

### ISSUE THREAD

**Issue by benwbrum** [IIIF/presentation-validator#110]
The spec states that _A Manifest must have the label property with at least one entry._  Currently the validator does not test for the presence of the `label` element in 3.0 manifests.  

To reproduce:
* Inspect https://iiif.io/api/cookbook/recipe/0014-accompanyingcanvas/manifest.json and verify that no `label` element exists for the manifest itself.
* Run the online validator with https://iiif.io/api/cookbook/recipe/0014-accompanyingcanvas/manifest.json
* The manifest should be invalid, but no errors are detected.

**Comment by glenrobson** [comment]
I believe this is fixed in: https://github.com/IIIF/presentation-validator/commit/36b3e9d7f3e222ecf43901062fdda76ed42582da

and I've tested it locally now and it does pick up a missing label.
