### ISSUE TITLE
Validation Error not clear enough to troubleshoot

### ISSUE THREAD

**Issue by bertramlyons** [IIIF/presentation-validator#111]
Validation Error: Presentation Validator bug: "". Please create a Validator Issue, including a link to the manifest.

Testing this v3 manifest: [https://raw.githubusercontent.com/WeAreAVP/aviary-iiif-test-samples/master/buffalo_trace_interview/manifest.json](https://raw.githubusercontent.com/WeAreAVP/aviary-iiif-test-samples/master/buffalo_trace_interview/manifest.json)

**Comment by glenrobson** [comment]
I'm just clearing up some old tickets and testing your manifest above now seems to give some clearer error messages. I'm closing this ticket but feel free to re-open if you disagree.
