### ISSUE TITLE
Possible improvement: including https version of licences links?

### ISSUE THREAD

**Issue by giacomomarchioro** [IIIF/presentation-validator#117]
Hello! 
The [example manifest response](https://iiif.io/api/presentation/3.0/#b-example-manifest-response) uses the HTTPS version of the licence page resulting in an invalid JSON for the current schema where these are not included.

https://github.com/IIIF/presentation-validator/blob/d4d376e46c966426e6a82e982ea40e149de4819f/schema/iiif_3_0.json#L217-L236

Maybe the https version could be added to the JSON schema?

**Comment by glenrobson** [comment]
Hi Giacomo,

I'm afraid the spec requires http in this section:

https://iiif.io/api/presentation/3.0/#rights

and there was a long discussion here on what to go for either http or https:

https://github.com/IIIF/api/issues/1874

Your absolutely right though, the example does show a https url for the rights. I will submit a issue in the API repo to get this changed.

**Comment by glenrobson** [comment]
I've submitted an issue here: https://github.com/IIIF/api/issues/2010

**Comment by giacomomarchioro** [comment]
Thanks a lot, Glen, sorry, my mistake I think I missed this point when I read the specs!
