### ISSUE TITLE
Presentation API validator should allow additional contexts

### ISSUE THREAD

**Issue by tomcrane** [IIIF/presentation-validator#13]
{
  "@context": [
    "http://iiif.io/api/presentation/2/context.json",
    "http://wellcomelibrary.org/ld/iiif-ext/0/context.json"
  ],

That gives "Validation Error: Top level @context is not known"

...but surely this is OK?

Test: http://wellcomelibrary.org/iiif/b18035978/manifest

(there are some other issues with that manifest)

**Comment by azaroth42** [comment]
The spec says:
> Any additional fields beyond those defined in this specification should be mapped to RDF predicates using further context documents. In this case, the enclosing object must have its own @context property, and it should be the first key/value pair of that object. This is required for service links that embed any information beyond a profile. These contexts should not redefine profile.

The intent was that it would live only where needed, rather than at the top level ... but if it's needed for the Manifest, that is the top level.  I think we should clarify in 2.1 that context MAY be a list to de-mystify this.

**Comment by tomcrane** [comment]
I have since moved what I was trying to assert at the manifest level to a service with its own context, which is better, but I agree that someone may need to do this for whatever reason and anyone processing a manifest should deal with multiple contexts.

The same discussion from the founding fathers: https://github.com/json-ld/json-ld.org/issues/32

**Comment by zimeon** [comment]
This is one of these issues where we need to think about whether how restrictive a profile of JSON-LD we are specifying. We are already doing a profile by demanding that a specific context is used, and the benefit of this is that the documents are readable as JSON by non-JSON-LD aware clients. IMO, we should place as few additional restrictions as possible and agree that "we should clarify in 2.1 that context MAY be a list to de-mystify this".

**Comment by azaroth42** [comment]
So we did clarify in 2.1 that this is okay. We should build a fixture object to test both at inner levels and at the top.
