### ISSUE TITLE
Is the https version of creativecommons.org an incorrect rights url?

### ISSUE THREAD

**Issue by nicolasfranck** [IIIF/presentation-validator#149]
If I put this url in the `rights` of my v3 IIIF manifest:

https://creativecommons.org/licenses/by-nc/4.0/

 the JSON schema for v3 complains that this url isn't valid.
Apparently it should be http://creativecommons.org/licenses/by-nc/4.0/,
so with `http` instead of `https`. Is that stated somewhere that the
http versions should be used, or is this simply a missing validation rule?

**Comment by glenrobson** [comment]
Hi,

I'm afraid it does have to be http. The [spec says](https://iiif.io/api/presentation/3.0/#rights):

"The value must be a string. If the value is drawn from Creative Commons or RightsStatements.org, then the string must be a URI defined by that specification."

and there is a long discussion in the following issue about which is the conical version and it was decided that http is for Creative commons:

https://github.com/IIIF/api/issues/1874
