### ISSUE TITLE
Validator considers Public Domain Mark invalid

### ISSUE THREAD

**Issue by DavidHaskiya** [IIIF/presentation-validator#169]
Hi,
When we tested our manifests we got an error from the validator for using https://creativecommons.org/publicdomain/mark/1.0/  as our rights value.

Is that as intended? 

![presentationvalidator_invalidPDM](https://github.com/IIIF/presentation-validator/assets/6057040/d40e816a-cb8f-4af1-acba-ffbc4545ab45)

**Comment by glenrobson** [comment]
It should be OK with the reg ex expression here: https://github.com/IIIF/presentation-validator/blob/c3283776ef60161e40677ac96632fa507602c0aa/schema/iiif_3_0.json#L259

```
{
                    "type": "string",
                    "format": "uri",
                    "pattern": "http://creativecommons.org/publicdomain/.*"
},
```

Do you have the manifest aviliable so I can test?

**Comment by DavidHaskiya** [comment]
Sure! Here's a manifest that throws the error, https://lbiiif.riksarkivet.se/arkis!R0003158/manifest

**Comment by mikeapp** [comment]
Use `http` see  https://github.com/IIIF/api/issues/1874

**Comment by glenrobson** [comment]
Ah yes sorry I didn't notice it was https and as Mike mentions that will be why its failing validation.

**Comment by DavidHaskiya** [comment]
Thank you! We will fix that in our next sprint!
