### ISSUE TITLE
Validate separately for version 2.X

### ISSUE THREAD

**Issue by azaroth42** [IIIF/presentation-validator#19]
Currently the validator can distinguish between 1.0 and 2.0 ... but the context will not be sufficient to distinguish 2.0 and 2.1.  Need to be able to allow validation separately... which doesn't fit nicely with the current single factory approach.

That said, 2.1 will be 100% backwards compatible with 2.0. So we could validate only against the most recent 2.X release.  The exception might be warnings ... if there's a new field that is recommended, it would generate a warning for previous versions where it did not exist.

**Comment by acdha** [comment]
Would it make sense to annotate the context document with a minimum version for elements so the validator could e.g. report errors for something which every 2.x version requires but only not that e.g. a document presented as 2.0 has a field which was added in 2.1.

That would also allow a path for deprecation if that becomes useful in the future by setting a max version for fields which should no longer be presented at some point.

**Comment by azaroth42** [comment]
Newly in iiif-prezi are the 2.1 fields and viewingHints.  If the factory is set to be 2.0, then it will raise an error on them.

**Comment by azaroth42** [comment]
This is closed by the most recent iiif-prezi work on 2.1 fields, per above comment.
