### ISSUE TITLE
Support validation of local manifests

### ISSUE THREAD

**Issue by schwemmer** [IIIF/presentation-validator#22]
Right now, the two options to validate a manifest are

a) use a GET request (so the manifest URI needs to be publicly available) or 
b) download the validator code and host it yourself

It would be great to have another option: 
c) send local manifest JSON to validator

so we could validate manifests before making them public and without having to install the validator locally. 

A use case would be if we were to build a stand-alone web application that creates manifests. The application could run locally and still support validation of IIIF manifests by sending the JSON to the validator (perhaps via POST). 

The W3C Markup validator supports validating local HTML. A number of browser add-ons such as the web developer add-on allow you to send your local HTML to the W3C validator.

**Comment by regisrob** [comment]
+1
Would be handy, for example to quickly validate a few BnF manifests that are not yet available online... but only as attached file in email :unamused:

**Comment by azaroth42** [comment]
This is done, you can POST the JSON to the validator's endpoint.  (/api/presentation/validate)

**Comment by schwemmer** [comment]
Thanks, Rob! I'm having some problems getting this to work. I think the issue here is that the server does not allow OPTIONS requests from any origin. I am getting the following error:

`XMLHttpRequest cannot load http://iiif.io/api/presentation/validate. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

Looks like the preflight request is blocked because it is an OPTIONS and not a POST request. See here for more information about preflight requests: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

Adding OPTIONS to the `Access-Control-Request-Method` on the validator server might fix this.

**Comment by azaroth42** [comment]
That's not the right URL.  You should try:  http://iiif.io/api/presentation/validator/service/validate

**Comment by schwemmer** [comment]
Ok, thanks Rob. But unfortunately, the issue remains the same. I am getting this error:

`XMLHttpRequest cannot load http://iiif.io/api/presentation/validator/service/validate. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 405.`

This is – I think – because the preflight request (that I can not prevent from happening) is using the OPTIONS method and only the POST method is allowed for for cross-origin-requests. From the network tab of the developer tools:

Request URL:http://iiif.io/api/presentation/validator/service/validate
Request Method:OPTIONS
Status Code:405 Method Not Allowed

**Comment by tomcrane** [comment]
[from sofware devs group meeting, Vatican)

@azaroth42 - @schwemmer is calling the validator from a browser via XHR rather than (say) curl, hence the additional preflight request that the validator is not allowing.

**Comment by stephenwf** [comment]
https://github.com/IIIF/presentation-validator/blob/master/iiif-presentation-validator.py#L119

The code here implies it already adds headers to option requests

**Comment by schwemmer** [comment]
@stephenwf Yes, looks like it. Maybe the latest code hasn't been deployed?

**Comment by azaroth42** [comment]
Try again? I updated the server to have the latest master from the GH repo, plus all the latest dependencies.

**Comment by schwemmer** [comment]
It's working now! However, I'm getting a "Error: 413 Request Entity Too Large" on some manifests. Shall I file a separate issue?

**Comment by azaroth42** [comment]
Yes please. That one might have to wait until we get our technical coordinator ... 413 isn't in the code, so it must be some configuration somewhere in Apache or Amazon :(

**Comment by schwemmer** [comment]
Done: #53 Error 413 "Request Entity Too Large" when validating via POST
