### ISSUE TITLE
Validator should allow common entities

### ISSUE THREAD

**Issue by azaroth42** [IIIF/presentation-validator#23]
In HTML such as &amp;nbsp;

**Comment by zimeon** [comment]
I certainly support the addition of support for numeric entities (`&#nnnn;` & `&#xhhhh`). I wonder whether we should discourage/reject named entities (`&name;`) which, depending on the environment the data is used in, may or may not be available?

**Comment by azaroth42** [comment]
&amp; &lt; and &gt; should always be available, no?

**Comment by zimeon** [comment]
Yes, I think that is true

**Comment by zimeon** [comment]
If I recall correctly, &quot; is very generally available too. &apos; is part of [XML 1.0](https://www.w3.org/TR/REC-xml/#sec-predefined-ent) but not part of all versions of HTML/XHTML.
