### ISSUE TITLE
Validator doesn't check Manifest URI is dereferencable

### ISSUE THREAD

**Issue by azaroth42** [IIIF/presentation-validator#57]
Should issue a warning, even though the requirement is MUST, as the manifest might not yet be public and don't want to stop the other validation tests.

**Comment by zimeon** [comment]
I agree that warning even though MUST is most useful to the community

**Comment by mikeapp** [comment]
👍 to issuing a warning

**Comment by glenrobson** [comment]
Added ERROR but only after all the other tests have passed or failed in this pull request:
