### ISSUE TITLE
No support for IIIF 2 image service in IIIF 3

### ISSUE THREAD

**Issue by markpatton** [IIIF/presentation-validator#78]
It looks like the validator does not like `@id` and `@type` being used for an IIIF 2 image service.

But the specification recommends:
```
service: [
  {
      "@id": "https://example.org/iiif2/image1/identifier",
      "@type": "ImageService2",
      "profile": "http://iiif.io/api/image/2/level2.json"
    }
]
```
The manifest I am experimenting with can be grabbed here:
https://rosetest.library.jhu.edu/rosademo/iiif3/rose/SeldenSupra57/manifest

**Comment by glenrobson** [comment]
Thanks Mark, Ill look into this.
