### ISSUE TITLE
Manifest Factory should be a module

### ISSUE THREAD

**Issue by azaroth42** [IIIF/presentation-validator#8]
With Pypi and distutils and all that lovely stuff.  Any takers?

**Comment by aeschylus** [comment]
@mekarpeles? 

Could this be a chance to show off [pypc](https://github.com/mekarpeles/pypc)?

**Comment by mekarpeles** [comment]
@azaroth42, @aeschylus 
Sure, pypc https://github.com/mekarpeles/pypc <https://pypi.python.org/pypi/pypc> will generate the basic scaffolding for your python project. It's not officially a component of pypa's `pip` tool yet and still requires some tweaking, but should save you a bit of time.

    $ sudo pip install pypc
    $ mkdir project;cd project
    $ pypc <project>

**Comment by mekarpeles** [comment]
https://github.com/mekarpeles/manifest-factory/tree/T8/feature/pypa-pkg
This is approximately what manifest-factory would look like as a standalone package called "mf". Likely doesn't run by itself yet, but the scaffolding, structure, etc should basically be there.

**Comment by azaroth42** [comment]
Oh nice! Will try and merge today :) Many thanks @mekarpeles!

**Comment by mekarpeles** [comment]
Its not ready, just scaffolded correctly. Drew or I will submit a pull
request when it's working+tested.

**Comment by azaroth42** [comment]
It now is, and has been for ages. (iiif-prezi)
